apiVersion: networking.istio.io/v1beta1
kind: Gateway
metadata:
  name: nginx-gateway
  namespace: istio-ingressgateway
  annotations:
    external-dns.alpha.kubernetes.io/hostname: "harsh-agrawal.me"
spec:
  selector:
    app.kubernetes.io/name: ingress-nginx
  servers:
    - port:
        number: 443
        name: https
        protocol: HTTPS
      tls:
        mode: SIMPLE
        credentialName: grafana-tls
      hosts:
        - "grafana.harsh-agrawal.me"
    - port:
        number: 80
        name: http
        protocol: HTTP
      tls:
        httpsRedirect: true
      hosts:
        - "grafana.harsh-agrawal.me"


