kraft:
  enabled: true



persistence:
  enabled: true
  size: 8Gi




controller:
  replicaCount: 3
  resources:
    limits:
      cpu: 2
      memory: 2048Mi
    requests:
      cpu: 1
      memory: 2048Mi




listeners:
  client:
    name: PLAINTEXT
    protocol: PLAINTEXT
    port: 9092
  controller:
    name: CONTROLLER
    protocol: PLAINTEXT
    port: 9093
  interBroker:
    name: INTERBROKER
    protocol: PLAINTEXT
    port: 9094



provisioning:
  enabled: true
  topics:
    - name: 'cve'
      partitions: 2
      replicationFactor: 2

metrics:
  jmx:
    enabled: true
  serviceMonitor:
    enabled: true
    namespace: monitoring
    labels:
      release: kube-prometheus-stack
    selector:
      app.kubernetes.io/name: kafka
    annotations:
      prometheus.io/scrape: "true"
      prometheus.io/port: "{{ .Values.metrics.jmx.service.ports.metrics }}"
      prometheus.io/path: "/metrics"
